import { Client } from '@easylayer/transport-sdk';
const client = new Client({ transport: { type: 'shared-worker', options: { url: '/worker.js', queryTimeoutMs: 15_000 } } });
let liveInterval: ReturnType<typeof setInterval> | null = null;
function log(message: string) { const el = document.getElementById('log')!; const div = document.createElement('div'); div.className = 'log-entry'; div.textContent = `[${new Date().toLocaleTimeString()}] ${message}`; el.prepend(div); while (el.children.length > 80) el.removeChild(el.lastChild!); }
async function queryBalance() { const input = document.getElementById('addresses') as HTMLInputElement; const addresses = input.value.split(',').map((value) => value.trim()).filter(Boolean); log(`→ GetBalanceQuery { addresses: [${addresses.join(', ')}] }`); try { const result = await client.query('GetBalanceQuery', { addresses }); document.getElementById('result')!.textContent = JSON.stringify(result, null, 2); log(`← ${JSON.stringify(result)}`); } catch (error: any) { document.getElementById('result')!.textContent = '⚠ ' + error.message; log(`← error: ${error.message}`); } }
function toggleLive() { const btn = document.getElementById('btn-live')!; if (liveInterval) { clearInterval(liveInterval); liveInterval = null; btn.textContent = '▶ Live (3s)'; log('Live updates stopped'); } else { queryBalance(); liveInterval = setInterval(queryBalance, 3000); btn.textContent = '⏹ Stop Live'; log('Live updates started'); } }
(window as any).queryBalance = queryBalance; (window as any).toggleLive = toggleLive; (window as any).openNewTab = () => window.open(window.location.href, '_blank');
async function waitForWorker() { const statusEl = document.getElementById('status')!; const btnQuery = document.getElementById('btn-query') as HTMLButtonElement; log('Connecting to SharedWorker...'); client.ping(); const deadline = Date.now() + 30_000; const check = () => { if (client.isOnline()) { statusEl.textContent = '✅ SharedWorker ready (crawler running)'; statusEl.className = 'status ready'; btnQuery.disabled = false; log('SharedWorker online — pong received'); queryBalance(); return; } if (Date.now() < deadline) { client.ping(); setTimeout(check, 1000); } else { statusEl.textContent = '❌ SharedWorker did not respond'; log('Timeout waiting for SharedWorker'); } }; setTimeout(check, 500); }
waitForWorker();
