name: 'Prepare Development Branch Before Release Flow'

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'patch, minor, major or release (to remove prerelease suffix)'
        required: true
        default: 'patch'
        type: choice
        options:
          - patch
          - minor
          - major
          - release

jobs:
  publish:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/development'
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          tags: true
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies in current repository
        uses: ./.github/actions/yarn-nm-install

      - name: Run Prepare Branch Script
        id: invoke_prepare
        run: bash ./scripts/prepare-branch-before-release.sh
        env:
          VERSION: ${{ github.event.inputs.version }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          HUSKY: '0'